import uuid
import logging
from datetime import datetime
from motor.motor_asyncio import AsyncIOMotorGridFSBucket
from models.artifacts import ArtifactMetadata, ArtifactRef, ArtifactContentResponse
from services.mongo import MongoDBManager, get_mongo_manager
from config.settings import get_settings

logger = logging.getLogger(__name__)


class ArtifactStore:
    def __init__(self, mongo: MongoDBManager | None = None):
        self.mongo = mongo or get_mongo_manager()
        self.settings = get_settings()
        self._memory_artifacts: dict[str, dict] = {}

    async def write_artifact(
        self,
        workflow_id: str,
        node_id: str | None,
        agent_id: str,
        name: str,
        content: str,
        artifact_type: str = "markdown",
        summary: str | None = None
    ) -> ArtifactRef:
        artifact_id = f"art-{uuid.uuid4().hex[:10]}"
        content_bytes = content.encode("utf-8")
        size_bytes = len(content_bytes)

        metadata = ArtifactMetadata(
            artifact_id=artifact_id,
            workflow_id=workflow_id,
            node_id=node_id,
            agent_id=agent_id,
            name=name,
            artifact_type=artifact_type,
            size_bytes=size_bytes,
            storage_backend="gridfs" if self.mongo.is_connected else "filesystem",
            storage_key=artifact_id,
            summary=summary or f"{artifact_type.capitalize()} artifact generated by {agent_id}"
        )

        if self.mongo.is_connected and self.mongo.db is not None:
            # Store in internal orchestrator collection
            await self.mongo.db.dwf_artifacts.replace_one(
                {"_id": artifact_id},
                {
                    "_id": artifact_id,
                    "metadata": metadata.model_dump(mode="json"),
                    "content": content
                },
                upsert=True
            )
            # Sync to canonical workflow_artifacts collection queried by live Azure agents
            await self.mongo.db.workflow_artifacts.replace_one(
                {"_id": artifact_id},
                {
                    "_id": artifact_id,
                    "artifact_id": artifact_id,
                    "job_id": workflow_id,
                    "workflow_job_id": workflow_id,
                    "workflow_id": workflow_id,
                    "node_id": node_id,
                    "agent_id": agent_id,
                    "name": name,
                    "artifact_name": name,
                    "type": artifact_type,
                    "artifact_type": artifact_type,
                    "content": content,
                    "artifact_content": content,
                    "summary": metadata.summary,
                    "metadata": metadata.model_dump(mode="json"),
                    "created_at": datetime.utcnow()
                },
                upsert=True
            )
        else:
            self._memory_artifacts[artifact_id] = {
                "metadata": metadata.model_dump(mode="json"),
                "content": content
            }

        return ArtifactRef(
            artifact_id=artifact_id,
            name=name,
            artifact_type=artifact_type,
            size_bytes=size_bytes,
            summary=metadata.summary,
            download_url=f"/api/dynamic-workflow/{workflow_id}/artifacts/{artifact_id}"
        )

    async def read_artifact(self, artifact_id: str) -> ArtifactContentResponse | None:
        if self.mongo.is_connected and self.mongo.db is not None:
            doc = await self.mongo.db.dwf_artifacts.find_one({"_id": artifact_id})
            if not doc:
                return None
            metadata = ArtifactMetadata(**doc["metadata"])
            content = doc.get("content", "")
            return ArtifactContentResponse(
                metadata=metadata,
                content=content,
                is_truncated=False,
                total_bytes=len(content.encode("utf-8"))
            )
        else:
            doc = self._memory_artifacts.get(artifact_id)
            if not doc:
                return None
            metadata = ArtifactMetadata(**doc["metadata"])
            content = doc.get("content", "")
            return ArtifactContentResponse(
                metadata=metadata,
                content=content,
                is_truncated=False,
                total_bytes=len(content.encode("utf-8"))
            )

    async def read_artifact_section(self, artifact_id: str, offset: int = 0, limit: int = 4096) -> ArtifactContentResponse | None:
        res = await self.read_artifact(artifact_id)
        if not res:
            return None
        full_content = res.content
        sliced = full_content[offset : offset + limit]
        res.content = sliced
        res.is_truncated = (offset + limit) < len(full_content)
        return res


_artifact_store_instance: ArtifactStore | None = None


def get_artifact_store() -> ArtifactStore:
    global _artifact_store_instance
    if _artifact_store_instance is None:
        _artifact_store_instance = ArtifactStore()
    return _artifact_store_instance
