import asyncio
from typing import Any
from models.workflow import StandardAgentResponse, NextAction


class MockAgentClient:
    """Provides high-fidelity mock responses for all 5 agents during local dev and testing."""

    async def invoke_agent(
        self,
        agent_id: str,
        task_type: str,
        input_data: dict[str, Any],
        context: dict[str, Any] | None = None
    ) -> dict[str, Any]:
        await asyncio.sleep(0.1)  # Simulate brief processing delay
        context = context or {}
        scenario = input_data.get("mock_scenario") or context.get("mock_scenario", "normal")
        invocation_count = input_data.get("invocation_count", 1)

        handler_name = f"_mock_{agent_id.replace('-', '_')}"
        handler = getattr(self, handler_name, self._mock_generic)
        return await handler(task_type, input_data, scenario, invocation_count, context)

    async def _mock_business_analyst(
        self, task_type: str, input_data: dict[str, Any], scenario: str, invocation_count: int, context: dict[str, Any]
    ) -> dict[str, Any]:
        query = input_data.get("prompt") or input_data.get("user_message") or context.get("query", "Business Workflow")
        
        if scenario == "error" and invocation_count == 1:
            return {
                "status": "error",
                "message": "Temporary connection timeout to BA Agent knowledge base",
                "data": {}
            }

        brd_content = f"""# Business Requirements Document (BRD)
## Project: {query}
**Generated by:** Business Analyst Agent (Version 1.0.0)
**Status:** Approved for Architectural Review

### 1. Executive Summary
This document outlines the end-to-end business requirements for {query}. The objective is to deliver high-throughput, secure, and scalable capabilities adhering to enterprise compliance standards.

### 2. Functional Requirements
- **FR-1:** Secure Multi-Factor User Authentication & RBAC.
- **FR-2:** Dynamic Transaction Orchestration with Idempotency.
- **FR-3:** Real-time Webhook Notifications & Audit Trails.
- **FR-4:** Automated Reconciliation & Settlement Reporting.

### 3. Non-Functional Requirements
- **NFR-1 (Latency):** 99.9th percentile response time under 200ms.
- **NFR-2 (Availability):** 99.99% uptime with multi-region disaster recovery.
- **NFR-3 (Security):** PCI-DSS Level 1 and SOC2 Type II compliance.

### 4. User Stories & Acceptance Criteria
1. *As a customer*, I want seamless checkout with payment tokenization so my card data is never stored locally.
2. *As an admin*, I want a unified dashboard to inspect live transactions and system health.
"""
        return {
            "success": True,
            "status": "completed",
            "message": "BRD and Requirements generated successfully",
            "data": {
                "artifact_name": "BRD_Payment_Platform.md",
                "artifact_type": "markdown",
                "artifact_content": brd_content,
                "summary": "Comprehensive Business Requirements Document covering functional & non-functional criteria.",
                "user_stories_count": 4,
                "confidence": 0.98,
                "next_action": {
                    "type": "request_human",
                    "reason": "Human approval required for final BRD signoff before architectural design."
                } if scenario == "hitl_required" else {"type": "none"}
            }
        }

    async def _mock_architect(
        self, task_type: str, input_data: dict[str, Any], scenario: str, invocation_count: int, context: dict[str, Any]
    ) -> dict[str, Any]:
        # If dynamic replanning scenario is requested or triggered on first run
        if scenario == "dynamic_replan" and invocation_count == 1:
            return {
                "success": True,
                "status": "needs_input",
                "message": "Architectural review identified ambiguity in transaction reconciliation requirements.",
                "data": {
                    "summary": "Clarification required on multi-currency settlement windows and webhook retry policy.",
                    "confidence": 0.85,
                    "next_action": {
                        "type": "request_agent",
                        "agent_id": "business-analyst",
                        "task_type": "dynamic_workflow_ba_task",
                        "reason": "BA clarification required for 3-D Secure multi-currency settlement window.",
                        "input_patch": {
                            "prompt": "Clarify multi-currency settlement windows and webhook retry policy for the BRD."
                        }
                    }
                }
            }

        arch_content = """# System Architecture Design Specification
## Target Solution: High-Scale Cloud-Native Platform

### 1. Architectural Overview
The system follows an event-driven microservices architecture hosted on Azure Kubernetes Service (AKS) with Cosmos DB and Azure Service Bus.

### 2. Component Diagram (Mermaid)
```mermaid
graph TD
    Client[Web & Mobile Clients] --> APIGateway[Azure API Management]
    APIGateway --> AuthSvc[Auth & Identity Service]
    APIGateway --> CoreSvc[Transaction Core Service]
    APIGateway --> ReconcileSvc[Reconciliation Service]
    
    CoreSvc --> EventBus[(Azure Service Bus)]
    EventBus --> NotificationWorker[Notification Worker]
    EventBus --> AuditWorker[Audit Logger]
    
    CoreSvc --> DB[(Azure Cosmos DB / Mongo API)]
    ReconcileSvc --> DB
```

### 3. Technology Stack
- **API Layer:** FastAPI / Python 3.11 + AsyncIO
- **Event Mesh:** Azure Service Bus (Pub/Sub)
- **Primary Data Store:** Azure Cosmos DB (MongoDB API)
- **Cache:** Redis Enterprise
- **Security:** OAuth2 / OpenID Connect + Azure Key Vault
"""
        return {
            "success": True,
            "status": "completed",
            "message": "System Architecture design and C4 diagrams created",
            "data": {
                "artifact_name": "System_Architecture_Design.md",
                "artifact_type": "markdown",
                "artifact_content": arch_content,
                "summary": "Event-driven microservices architecture with Mermaid diagram, CosmosDB data layer, and OAuth2 security.",
                "diagram_format": "mermaid",
                "confidence": 0.96,
                "next_action": {"type": "none"}
            }
        }

    async def _mock_developer(
        self, task_type: str, input_data: dict[str, Any], scenario: str, invocation_count: int, context: dict[str, Any]
    ) -> dict[str, Any]:
        code_content = """# Implementation Scaffolding & Core Microservice
import asyncio
from fastapi import FastAPI, HTTPException, status
from pydantic import BaseModel, Field

app = FastAPI(title="Payment Orchestration Service", version="1.0.0")

class PaymentRequest(BaseModel):
    transaction_id: str
    amount: float = Field(gt=0)
    currency: str = Field(default="USD", max_length=3)
    payment_method: str = "tokenized_card"

class PaymentResponse(BaseModel):
    transaction_id: str
    status: str
    auth_code: str

@app.post("/api/v1/payments", response_model=PaymentResponse, status_code=status.HTTP_201_CREATED)
async def process_payment(req: PaymentRequest):
    # Idempotent processing logic
    return PaymentResponse(
        transaction_id=req.transaction_id,
        status="AUTHORIZED",
        auth_code="AUTH-994821"
    )
"""
        return {
            "success": True,
            "status": "completed",
            "message": "Core implementation scaffolding and services generated",
            "data": {
                "artifact_name": "Implementation_Scaffold.py",
                "artifact_type": "code",
                "artifact_content": code_content,
                "summary": "FastAPI production microservice boilerplate with Pydantic validation and idempotency.",
                "confidence": 0.95,
                "next_action": {"type": "none"}
            }
        }

    async def _mock_product_owner(
        self, task_type: str, input_data: dict[str, Any], scenario: str, invocation_count: int, context: dict[str, Any]
    ) -> dict[str, Any]:
        po_content = """# Sprint Planning & Backlog Prioritization
## Release: MVP Sprint 1 & Sprint 2

### Sprint 1: Foundation & Core APIs (Velocity: 24 pts)
1. **US-101 (8 pts):** Setup Azure API Management and OAuth2 JWT authentication.
2. **US-102 (8 pts):** Implement Core Payment Processing API with Idempotency.
3. **US-103 (5 pts):** Configure MongoDB Cosmos DB collections & indexes.
4. **US-104 (3 pts):** Health check and distributed tracing with OpenTelemetry.

### Sprint 2: Integration & Webhooks (Velocity: 22 pts)
1. **US-201 (8 pts):** Azure Service Bus asynchronous event publisher.
2. **US-202 (8 pts):** Webhook dispatcher with exponential retry policy.
3. **US-203 (6 pts):** End-to-end reconciliation batch job.
"""
        return {
            "success": True,
            "status": "completed",
            "message": "Sprint plan and backlog prioritization completed",
            "data": {
                "artifact_name": "Sprint_Plan_MVP.md",
                "artifact_type": "markdown",
                "artifact_content": po_content,
                "summary": "Sprint 1 and Sprint 2 backlog breakdown with story points and acceptance criteria.",
                "confidence": 0.97,
                "next_action": {"type": "none"}
            }
        }

    async def _mock_qe(
        self, task_type: str, input_data: dict[str, Any], scenario: str, invocation_count: int, context: dict[str, Any]
    ) -> dict[str, Any]:
        qe_content = """# Quality Engineering & Test Strategy
## Test Automation Suite Specification

### 1. Test Coverage Matrix
- **Unit Tests:** > 90% code coverage on core domain logic.
- **Integration Tests:** Contract verification on API gateway and Cosmos DB repositories.
- **Security Tests:** OWASP Top 10 automated scans with ZAP & token expiration tests.
- **Performance:** 500 concurrent virtual users at 2500 req/sec using Locust.

### 2. Automated Test Scenarios
```python
import pytest
from httpx import AsyncClient

@pytest.mark.asyncio
async def test_payment_idempotency():
    async with AsyncClient(base_url="http://test") as ac:
        payload = {"transaction_id": "tx_123", "amount": 100.0, "currency": "USD"}
        r1 = await ac.post("/api/v1/payments", json=payload)
        r2 = await ac.post("/api/v1/payments", json=payload)
        assert r1.status_code == 201
        assert r2.status_code == 201
        assert r1.json()["auth_code"] == r2.json()["auth_code"]
```
"""
        return {
            "success": True,
            "status": "completed",
            "message": "Quality Engineering strategy and automated test suites generated",
            "data": {
                "artifact_name": "QE_Test_Strategy.md",
                "artifact_type": "markdown",
                "artifact_content": qe_content,
                "summary": "Comprehensive QA test strategy including unit, integration, performance, and security testing.",
                "confidence": 0.99,
                "next_action": {"type": "none"}
            }
        }

    async def _mock_generic(
        self, task_type: str, input_data: dict[str, Any], scenario: str, invocation_count: int, context: dict[str, Any]
    ) -> dict[str, Any]:
        return {
            "success": True,
            "status": "completed",
            "message": f"Generic mock execution for task {task_type}",
            "data": {
                "artifact_name": f"{task_type}_output.json",
                "artifact_type": "json",
                "artifact_content": '{"status": "ok"}',
                "summary": f"Executed {task_type} successfully.",
                "confidence": 0.9,
                "next_action": {"type": "none"}
            }
        }
